language: python
before_script:
    - pip install -r requirements-dev.txt
script:
    - flake8 -v pact_request
    - py.test --cov=pact_request
after_success:
    - pip install python-coveralls
    - coveralls
